spring:
  application:
    name: spring-reative-mongoapi

  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27017
      database: DataBaseProject
server:
 port: 8080
 
kafka:
  bootstrap-server: localhost:29092
  acks: all
  retries: 22785
  batch-size: 131072
  buffer-memory: 80000000
  client-id: producerEvent
  idempotence: true
  compression-type: lz4
  topic-name: stock-v1
  user: producer-user
  password: producer-pwd